apiVersion: v1
kind: Service
metadata:
  name: api-svc
  labels: #Etiquetas del servicio
    app: api
spec:
  type: NodePort #Puede ser contactado externamente
  ports:
    - port: 8000 #Comunicación interna dentro del cluster
      nodePort: 30000 #Para acceder externamente
      protocol: TCP
  selector: #Gestiona el deployment con la etiqueta
    app: api